apiVersion: v1
kind: Service
metadata:
 name: hello-web
 namespace: hello
spec:
 type: NodePort
 selector: { app: hello-web }
 ports:
   - port: 80
     targetPort: 9090
     nodePort: 30080
